apiVersion: v1
kind: Service
metadata:
    name: wilapp-service
spec:
    type: NodePort
    selector:
        app: wilapp
ports:
    - name: http
      port: 80
      targetPort: wilport
      nodePort: 30888
